version: '3.8'

services:
  mediaflow-proxy:
    image: mhdzumair/mediaflow-proxy:latest
    container_name: mediaflow-proxy
    restart: unless-stopped
    ports:
      - "8888:8888"
    environment:
      - API_PASSWORD=${MEDIAFLOW_API_PASSWORD:-your_password}

  stremio-addon:
    build: .
    container_name: stremio-addon
    restart: unless-stopped
    ports:
      - "${PORT:-7860}:${PORT:-7860}"
    volumes:
      - .:/app
    environment:
      # Server configuration
      - PORT=${PORT:-7860}
      - HOST=127.0.0.1
      - ADDON_BASE_URL=${ADDON_BASE_URL:-http://localhost:7860}
      # IMPORTANT: Use a client-reachable URL here (host IP or domain). Avoid Docker-internal hostnames.
      - MEDIAFLOW_PROXY_URL=${MEDIAFLOW_PROXY_URL:-http://host.docker.internal:8888}
      - MEDIAFLOW_API_PASSWORD=${MEDIAFLOW_API_PASSWORD:-your_password}
    # On Linux, enable host.docker.internal via host-gateway resolution
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mediaflow-proxy
